### ISSUE TITLE
Book: Resources page fails to center on mobile

### ISSUE THREAD

**Issue by HillbillyZT** [bevyengine/bevy-website#1]
All of the pages in the Bevy Book display well on mobile with the exception of the Resources page where the Time resource is introduced.

Using OnePlus 5T Chrome

All of the book files derive from the same template, so this is a bit curious.

**Comment by guimcaballero** [comment]
The issue seems to be with the `book-content` class. Adding `min-width: 0;` to this class fixes the issue for me in Firefox on macOS. I'm not sure if this addition breaks anything else on other pages or browsers, so I'm not confident enough to open a PR. Hope this saves some debugging time though.

It's really weird that it looks weird only for this page, it looks like all of them use the same css.

**Comment by cart** [comment]
Im unable to repro this in any of my browsers/devices, but the fix @guimcaballero provides doesn't appear to break anything, so I think ill just merge it and hope for the best :)
