### ISSUE TITLE
Add the ability to link to sections of news releases

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#125]
Very useful for 10k word blog posts like 0.5. Try to use standard tools for this to make sure screen-readers play nice.

**Comment by piedoom** [comment]
On this one, there's a couple of options

## 1. Manual

On a cursory search, there doesn't appear to be a way to have self-referential links.  This makes a markdown-only solution very tedious, as every header in the content pages would need to look like `## [myverylongheader](#myverylongheader)`. 

## 2. Auto Anchor insertion

Zola has a viable alternative with [anchor insertion](https://www.getzola.org/documentation/content/linking/#anchor-insertion). The downside of this is that there is apparently no way to pass the actual text in to create the link, which means we *must* show an additional item, like the `link` emoji. Thankfully, it appears that zola will still generate the necessary labels for screen readers, although they are slugified.

![image](https://user-images.githubusercontent.com/8846211/113951137-985e9e80-97d8-11eb-9389-d050b42b75ec.png)

![image](https://user-images.githubusercontent.com/8846211/113951289-e7a4cf00-97d8-11eb-8c41-cffddb842a64.png)

## 3. Custom shortcode

A custom shortcode, unfortunately, not be automatic like Zola's built-in, but it would provide us with a bit more flexibility. It appears we already mix in a fair amount of HTML with these articles anyways, so shortcodes shouldn't be too bad. 

In this case, 

```md
## GLTF Improvements

### PBR Textures
```

becomes

```md
{{ heading(text="GLTF Improvements") }}

{{ heading(text="PBR Textures", size=3) }}
```

and renders like

![image](https://user-images.githubusercontent.com/8846211/113952883-33a54300-97dc-11eb-8066-e3bd17c53657.png)

with proper a11y

![image](https://user-images.githubusercontent.com/8846211/113952908-428bf580-97dc-11eb-83c7-c71418ea6f06.png)

I think the CSS of this one can be tweaked a bit to look less like a link, if we want to go this direction. 

Please let me know if there are any questions, alternatives, or suggestions. I'm partial to option 3.

**Comment by alice-i-cecile** [comment]
I think I prefer option 2, since it makes clear that the segments can be linked to. It also seems a bit less obscure to write.

That said, I'm very impressed by option 3, particularly the fact that a11y is preserved so nicely.

**Comment by piedoom** [comment]
Makes sense to me, probably the easiest to maintain as well.

For links, there's some styling options. We can do a left aligned link, like on the zola docs.

![image](https://user-images.githubusercontent.com/8846211/113957201-69e6c080-97e4-11eb-8cfc-80eafdf8837f.png)

this is nice since the anchor is always in a regular spot, however it doesn't look as nice on smaller screens collapsed.

![image](https://user-images.githubusercontent.com/8846211/113957334-a0bcd680-97e4-11eb-8e2f-ba9a241c570b.png)

---

Or we could just do right aligned:

![image](https://user-images.githubusercontent.com/8846211/113957413-c9dd6700-97e4-11eb-9a1b-1e38f13ecd81.png)

However the links are a bit more difficult to find. 

---

I'm using a 🔗 emoji here, but it's also worth mentioning that it probably renders wildly differently depending on the device. Maybe a `#` would be more suitable?

**Comment by alice-i-cecile** [comment]
Arbitrary preference for right-aligned due to prettiness; grabbing the links should be relatively rare and typically only done by power users.

> I'm using a 🔗 emoji here, but it's also worth mentioning that it probably renders wildly differently depending on the device. Maybe a # would be more suitable?

I think the clarity is more important; I don't think we have strong demands on cross-device consistency for this.
