### ISSUE TITLE
0.14 Migration: Consolidate binned render phases changes

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy-website#1386]
The migration text for https://github.com/bevyengine/bevy/pull/13277 is talking about types that didn't exist in Bevy 0.13. I think it needs to be consolidated with https://github.com/bevyengine/bevy/pull/12453.

**Comment by alice-i-cecile** [comment]
Seconded by @djeedai [here](https://discord.com/channels/691052431525675048/1239930965267054623/1254176245965520956).

**Comment by djeedai** [comment]
There's another issue, which might be an actual code bug, or just a lack of documentation : I can't make `BinnedRenderPhase<AlphaMask3d>` to work with non-mesh items (particle effects for Hanabi). It seems that `batching::sort_binned_render_phase()` does run, but after that none of the GPU pre-processing / no-pre-processing prepare systems run, so the render phase items added are never rendered. I believe this is because they both have a render condition, based on a particular resource being present, but that part is not documented and I've yet to understand if/how I should add those resources.

CC: @pcwalton as I think you wrote all of that and know Hanabi very well, you probably know already the answer? :)

**Comment by rparrett** [comment]
It's possible you might find inspiration from [`bevy_ecs_tilemap`](https://github.com/StarArawn/bevy_ecs_tilemap/pull/537)'s migration -- maybe a similar situation there where we're doing some very custom stuff with non-`Mesh`s.

I struggled with these particular changes myself and gave up, hence the ticket. CC also @ChristopherBiscardi who might be able to help with the migration guide.

**Comment by ChristopherBiscardi** [comment]
I can try to help, I won't be able to look into it until Tuesday though.

**Comment by djeedai** [comment]
Nope, that migration doesn't help, there's nothing about binned render phase.

**Comment by ChristopherBiscardi** [comment]
its looking like https://github.com/bevyengine/bevy/pull/14029 will be included in this consolidation as well.

**Comment by BD103** [comment]
To summarize, the following migration guides need to be merged and improved:

- https://github.com/bevyengine/bevy/pull/13277
- https://github.com/bevyengine/bevy/pull/12453
- https://github.com/bevyengine/bevy/pull/14029

Feel free to ping me when you need a review, though I'll do more style than content checking. :)
