### ISSUE TITLE
`lint-tools` CI job fails after Rust 1.79 update

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy-website#1399]
[Here is an example of the failure.](https://github.com/bevyengine/bevy-website/actions/runs/9501144150/job/26185983274) This is likely due to a lint that was stabilized. It should probably be disabled for now, and a bug report may need to be opened depending on whether the behavior is correct or not.

**Comment by rparrett** [comment]
I don't see anything wrong with the behavior of this lint -- most of the errors are from us shoving zola frontmatter / shortcodes into rust docs.

We might need to rethink our current implementation of `code-validation` and do some sort of code generation / stripping out everything except code blocks instead. That might also help with the "formatting" problem described in https://github.com/bevyengine/bevy-website/pull/281.

Disabling the lint in `code-validation` for now seems like the right call to me though.

**Comment by TrialDragon** [comment]
Mm, a more long term solution is probably something related with the first solution for how to better do code blocks formatting / validating / usage in the book-related docs listed at https://github.com/bevyengine/bevy-website/issues/279#issuecomment-1979956811 since it side steps the code validator / this issue altogether in the long run.
