### ISSUE TITLE
Tera Templates don't seem to work in new release notes

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1424]
![image](https://github.com/bevyengine/bevy-website/assets/59022059/77840031-1fff-4834-806d-811c0e9c4f32)

_Originally posted by @BD103 in https://github.com/bevyengine/bevy-website/pull/1411#discussion_r1644646131_
        
 This is a pretty serious problem: it needs to have a resolution in some form before we can ship the notes.

**Comment by kristoff3r** [comment]
I looked at this a bit, and I don't think it's easy to solve. The problem is that the body is fetched with `load_data` and then put into the document raw, but that means that any templating inside isn't evaluated. If there was a way to do `eval` or dynamically include files we could just do that, but it seems like Tera supports neither.

Unless someone knows a workaround I think that makes it impossible to achieve with this new release note structure. We could have some custom code that takes all the snippets and generates the big static file instead of having Zola do it. Or maybe find a way to use some of the section support instead of the `.toml` parsing we currently do.

**Comment by kristoff3r** [comment]
I tried making a release note section and including that in a specialized release-news template, but 1) that would end up being a very invasive change 2) as far as I can see it wouldn't allow to control where the release notes appear in the content, it would have to be first or last. It feels to me like Zola is too opinionated towards simple blogs, there are multiple github issues where the author rejects features that would've solved this.

For this release, the only option I can think of if we want the sliders is to not use the `release_notes` shortcode and just manually concatenate the individual md files before we press publish, but then the new structure is pointless. I hope someone else can find a better solution.

**Comment by cart** [comment]
I experimented with the following structure, which _felt_ like it was going to work, but I hit a wall:

1. Define each section as an individual macro file (ex: `macros/release/0.14/section.md`)
2. Define a `release_notes_0_14` shortcode that imports each macro file and calls `{{ section::build() | markdown | safe }}`
3. Call the `release_notes_0_14` shortcode from the actual `index.md` for the release note news page.

This renders, but it doesn't allow the use of shortcodes because macros can't access shortcodes :cry:

I'm also pretty convinced that this isn't possible right now in zola.

**Comment by BD103** [comment]
> I'm also pretty convinced that this isn't possible right now in zola.

We could fork Zola, however difficult that may be.
