### ISSUE TITLE
`generate-release` has false-positives for migration guides

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy-website#1469]
Some PRs, such as https://github.com/bevyengine/bevy/pull/13271, have a `## Migration Guide` header with no content because they are not a breaking change. `generate-release` generates migration guides for these pull requests, and does not appear to respect the `C-Breaking-Change` label.

I haven't looked too deeply into the code, but I think `generate-release` should only generate guides for PRs that have the `C-Breaking-Change` label.

I uncovered this while re-running `generate-release` for Bevy 0.14.0-rc.4.

**Comment by IceSentry** [comment]
> but I think generate-release should only generate guides for PRs that have the C-Breaking-Change label.

That's what I did originally and then a ton of guides were missing because people wrote guides but never added the label. We explicitly modified the tool to look for migration guide entries without the label because of how common it was.

The only thing that can be done is check if a section is empty. In my experience it wasn't common at all though. So you might want to look at the offending PR and make sure they are actually empty. It's possible the tool is failing to write the content correctly.

**Comment by BD103** [comment]
Ah, that makes more sense. I don't think there's a good way to truly check that it's not a breaking change because sometimes authors write "N/A", "", and "Nothing needs to migrated." The only thing I can think of to detect that is an LLM, which is **definitely** not worth the effort to setup.

In this case, it's probably best to just remove these false-positives after the fact with #1457.

**Comment by IceSentry** [comment]
This PR should skip the empty guides and warn the person running the tool https://github.com/bevyengine/bevy-website/pull/1470
