### ISSUE TITLE
Changelog and contributors tools can fail to find PRs

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1518]
>  IMO: all of the missed PRs look like they got excluded because they were originally opened before the "from" date for the release

- @ChristopherBiscardi 

Discovered in #1516 / #1517.

**Comment by ChristopherBiscardi** [comment]
`get_issues_and_prs` gets all PRs since the origin date, which is going to be roughly `0.<last_major>.1`'s date. That set of PRs is what is [is checked](https://github.com/bevyengine/bevy-website/blob/4576f6b1fc4f4f66c9e063734fcbe2af688a986e/generate-release/src/helpers.rs#L48) so any PR opened before that will not be included because the issues endpoint can not be sorted by "closed date". I believe the default sorting for the issues endpoint is "id, descending".

The older PRs may have to be fetched by id.

**Comment by alice-i-cecile** [comment]
In #1850, I'm no longer filtering the PRs by date. This helps: we found another half-dozen PRs! It doesn't fully resolve the mismatch though :( Dozens of PRs were still not found.

**Comment by alice-i-cecile** [comment]
We're using a title match to correlate commits against PRs. In some cases, like https://github.com/bevyengine/bevy/pull/15320, that's definitely because we renamed the PR after it was merged, so the commit name and the PR title don't match. I have no good ideas for how to resolve that. 

But there's dozens of other PRs, which seemingly don't share that problem. See https://github.com/bevyengine/bevy/pull/14122 for example. The PR exists, it hasn't been renamed. Perhaps there's another date check that I'm missing?

**Comment by alice-i-cecile** [comment]
And by querying for *all* PRs and trying to match them, I get a much smaller list.

```rust
PR not found for bevy_reflect: Reflect remote types sha: 6183b56b5d6fd7e2e8cf1f3c85da7fd3dab25ea4
PR not found for Add `condition_changed` and `condition_became_true` to `common_conditions` sha: 12f005a024c163333455bfd8112893c6a8075716
PR not found for Depreciate `LoadAndSave` Asset Processor sha: dac4a5bbb4336527ffd0880233b92f5bc4f93c54
PR not found for bevy_reflect: Add `Reflectable` trait sha: 69541462c5ef70914fd719fcd1f503045c76a453
PR not found for The Cooler 'Retain Rendering World' sha: 56f8e526dde49b4e4ad62efb7ad27bfe0bd6f617
```
