### ISSUE TITLE
0.13 to 0.14 migration guide didn't mention `insert_gizmo_group`

### ISSUE THREAD

**Issue by onelson** [bevyengine/bevy-website#1551]
Just finished migrating a project to 0.14 🥳

Formerly I was calling `insert_gizmo_group` when building my app to configure gizmos for `bevy_xpbd` but now needed to use `insert_gizmo_config`.

I didn't see any mention of in the migration guide (this was the only thing I had to chase down myself instead of referring to what was in the guide).

**Comment by TrialDragon** [comment]
Good catch! It seems https://github.com/bevyengine/bevy/pull/10973 wasn't marked properly as having breaking changes and as such didn't have a migration guide / this change wasn't even mentioned in the PRs changelong nor comments from what I can see. (Off-topic, I wonder why only `insert_gizmo_group` was changed and not also `init_gizmo_group` since they seemed to be following same naming convention before this change; feels inconsistent now).

**Comment by BD103** [comment]
> (Off-topic, I wonder why only `insert_gizmo_group` / `insert_gizmo_config` was changed and not also `init_gizmo_group` since they seemed to be following same naming convention before this change; feels inconsistent now).

@Aceeri, would you be able to comment on this?

**Comment by Aceeri** [comment]
> > (Off-topic, I wonder why only `insert_gizmo_group` / `insert_gizmo_config` was changed and not also `init_gizmo_group` since they seemed to be following same naming convention before this change; feels inconsistent now).
> 
> @Aceeri, would you be able to comment on this?

Been a bit, but I don't super remember why I didn't rename both. I do remember thinking group just didn't fit the name very well for what it does, but I yeah we should rename them to have the same suffix for both.
