### ISSUE TITLE
Flatten book layout structure

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#160]
Rather than using `page-title/_index.md`, it would be very convenient to just be able to use `page-title.md`.

Unfortunately, I couldn't figure out how to get Zola to do this.

**Comment by TrialDragon** [comment]
Hey, I would like to tackle this issue. Already looked thru stuff and thought about it; main issue so far seems to be how to maintain order of pages and sections when creating the tree menu since they're separate objects and the arrays to get them per section don't actually include the weight or any of that, so it's just two sorted arrays with no indices to compare where position should be between the two.

**Comment by TrialDragon** [comment]
I think it could be sort of resolvable without any upstream changes. I could use the extras field of the front matter to store the weight instead so that each section and pages weight is accessible in the template. Issue with that is we'd more or less have to define weight twice: once in the regular Zola way for initial sorting and secondly in the extra fields so that we can actually use it.

Ideally tho, I will hopefully find something I overlooked that doesn't mean having to do weird stuff like this.

**Comment by alice-i-cecile** [comment]
The maintainer of Zola has been quite receptive in the past: if you can't figure out a good fix, don't hesitate to open a PR upstream instead :)
