### ISSUE TITLE
Write release notes for PR #14868: Allow fog density texture to be scrolled over time with an offset

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1677]
https://github.com/bevyengine/bevy/pull/14868 needs release notes for the upcoming Bevy release!

Please reply below if you'd like to write these notes. 
While the author(s) of the PR often have the context, knowledge and motivation to draft the release notes for their feature, anyone can contribute release notes!

------

Release notes should:

1. Clearly motivate the change.
2. Be written in a way that is understandable by the average Bevy user: some programming background and a general understanding of games.
3. Show off the coolest features of the PR. Screenshots are awesome, but elegant APIs are also welcome!
4. If this was a perf-centric PR, quantify the performance improvements. Graphs and statistics work well for this.

We can help you revise the release notes: a rough draft alone is incredibly useful :)
Your expertise is invaluable for contextualizing the changes; we'll work with you to bring the technical writing up to par.

To submit your release notes, modify `/home/alice/Documents/bevy-website/release-content/0.15/release-notes/14868_Allow_fog_density_texture_to_be_scrolled_over_time_with_an.md` and submit a PR.
In that PR, please mention this issue with the `Fixes #ISSUE_NUMBER` keyphrase so it gets closed automatically.

**Comment by jirisvd** [comment]
Since this is a small change built on top of the newly added fog volumes, I think it would make more sense for this to be mentioned at the bottom of #1661 as one possible use case of fog density textures (possibly with the video from bevyengine/bevy#14868 included). Something along the lines of "The `FogVolume` component also exposes a `density_texture_offset` field that can be used to move the density texture over time to create dynamic effects like fog moving in the wind."

I assume I should wait until #1661 release notes are written and then open a PR appending this extra info and updating `_release-notes.toml`?

**Comment by alice-i-cecile** [comment]
Yep, let's merge those two changes into one.

**Comment by alice-i-cecile** [comment]
Should be batched with #1745.
