### ISSUE TITLE
Fix broken short code syntax displayed in docs

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#210]
On https://bevyengine.org/learn/book/contributing/docs/ I see: 
![image](https://user-images.githubusercontent.com/3579909/129069567-261f971a-08e9-4453-a94e-602e5066d6d3.png)

**Comment by cart** [comment]
Hmm maybe this was the result of a recent Zola update? The shortcodes for open/close parens were built specifically for this section (and they used to work).

**Comment by alice-i-cecile** [comment]
That makes sense. It's failing locally for me too (now that I'm on 0.14).

Are you potentially on-board with just migrating this content to CONTRIBUTING.md here on Github? It's not very useful for new readers, and that lets us bypass the whole problem.

**Comment by cart** [comment]
I personally like having "contributing" content in the book for a number of reasons:

* It subtly sends the message to people new to Bevy that contributing is a core "part" of Bevy. 
* It shows new users how easy it is to contribute. If they are browsing The Book, they might just casually read through the Contributing section without explicitly seeking it out (which they would need to do for a Contributing.md  file). They might not think to seek it out because they might consider contributing "inaccessible". If its in The Book, we get a chance to "convert" them.
* It allows us to use The Book formatting and tooling, which are significantly "better" than raw markdown files or "github rendered markdown".

**Comment by alice-i-cecile** [comment]
I can get behind that. Ideally we can get some automatic synchronization with the CONTRIBUTING.md files in both repos?

**Comment by cart** [comment]
Can we just have our CONTRIBUTING.md link to the book? That eliminates the "sync" problem and ensures a consistent user experience.

**Comment by alice-i-cecile** [comment]
> Can we just have our CONTRIBUTING.md link to the book? That eliminates the "sync" problem and ensures a consistent user experience.

I'm on board with this. We should finish the reviews in https://github.com/bevyengine/bevy/pull/2040, add a section on short-codes to it, and then migrate it over to the website.

**Comment by cart** [comment]
Sounds good to me!
