### ISSUE TITLE
Search Functionailty (Make dicussions & discord visible)

### ISSUE THREAD

**Issue by BlackPhlox** [bevyengine/bevy-website#232]
## (WIP)
Part of #159 - Asset search
Related to #2 - Searchable bevy

Based on being active in the bevy discord help channel, some of the questions asked have already been discussed. In order to intrinsically prevent duplicates, we should use the website as a medium to redirect users for help.

Goal: 
Encourage discovery though:
- [Discussions](https://github.com/bevyengine/bevy/discussions)
- [Discord](https://discord.gg/bevy)
- Cheatbook (https://bevy-cheatbook.github.io)
in order to unify help in one place for new-comers and to promote bevy assets

Pros & Cons:
```diff
+  Not having the costs of hosting a database
-  Not as customizable as it relies on GitHub and crates.io APIs
```

Requires metadata tags from github and or crates.io specified in #230 

[Prototype](https://www.figma.com/file/CZ1svP4l70eMuPYXIOK9d3/bevy_design_sheet?node-id=612%3A58):

Where the URL looks something like `https://bevyengine.org/assets?q=hide+mouse`

And clicking on _Search for “hide mouse” in discussions_ links to: 
[`https://github.com/bevyengine/bevy/discussions?discussions_q=hide+mouse`](https://github.com/bevyengine/bevy/discussions?discussions_q=hide+mouse) and 
[`https://bevy-cheatbook.github.io/?search=hide%20mouse`](https://bevy-cheatbook.github.io/?search=hide%20mouse)
 for bevy-cheatbook

![Group 88](https://user-images.githubusercontent.com/25123512/147786940-f0c7a8fc-4757-4f9c-897d-e5b79740933e.png)

**Comment by alice-i-cecile** [comment]
https://dev-docs.bevyengine.org/bevy/index.html may also be worth searching, in addition to crates.io docs and the book.

**Comment by CooCooCaCha** [comment]
If we want search-as-you-type then we'll need javascript. 

Alternatively, it might be possible to implement search as an HTML form that refreshes the page every time a user searches. This would mean ditching zola in favor of a custom-built server that dynamically generates HTML. It's also, honestly, a sub-par user experience compared to search-as-you-type like the bevy cheatbook.

Either way, the dynamics need to take place somewhere since a purely static HTML + CSS site can't reconfigure itself based on user search input.

I haven't used any, but it seems there are some javascript search engines that are built to run in the browser. We could pair that with our own zola-generated javascript that uses the bevy-assets repo as a data source.

Additionally we'll have to think about how we want to update the DOM. Manually updating the DOM is error prone and doesn't scale as sites grow in functionality. It might be worth prototyping the manual route but if we keep going this direction I suspect we'll end up rediscovering why the modern UI frameworks exist :). Just my 2c.

**Comment by BlackPhlox** [comment]
Related #379

**Comment by d-bucur** [comment]
I have added a basic search in https://github.com/bevyengine/bevy-website/pull/734 

The search link to GH Discussions and Bevy cheatbook are easy to implement as a link, discord search is a can of worms I don't want to open.

But I have a problem with the UX of this proposal. If I am on the asset page and searching for assets I don't want the first results to be to something else entirely. And searching for an asset uses completely different terms than searching a problem in Discussions or cheatbook, so it's likely there will be no results.

I propose to display these links only as a final resort if either the search result in assets is empty, or at the bottom of the page if the user scrolled down and didn't find what they were looking for.

**Comment by BlackPhlox** [comment]
@d-bucur I agree, this is a much better approach, and UX.
