### ISSUE TITLE
Examples page and load times

### ISSUE THREAD

**Issue by Weasy666** [bevyengine/bevy-website#236]
About the examples on the website (or examples in general)...i think it would be a good idea to add some kind of loading animation to examples which have big assets. Especially `load_gltf` and `update_gltf_scene` need to load "big" assets and display only a grey rectangle until everything is loaded....which on the web, depending on the internet connection, can take a while. People could misunderstand that as "It's not working" and try to refresh the page or give up.

I know the example in Bevy need to be changed, but I'm opening the issue here, because i think it does not matter that much when you run the current examples locally, but it matters a lot on the web.

**Comment by mockersf** [comment]
Handling this directly in Bevy would require quite a bit of code added to the examples... I wonder if it would be possible to handle that in javascript?
At least adding a message to the page about load time is an easy win

**Comment by Weasy666** [comment]
Hm...dunno if you can use javascript to check if there are still some network requests going on. I don't think that a loading animation would be needed for every example, only the ones with big assets. ~~I have never done that and don't know if it is possible, can you share code between examples?~~ Looks like there is a way to [share](https://users.rust-lang.org/t/shared-lib-between-two-example-binaries/51670). Then we could create a loading animation example, make the systems "generic" and use them in examples with big assets.

**Comment by superdump** [comment]
The wasm is about 13MB. Just noting that.

**Comment by rparrett** [comment]
In some of my games I just add a loading indicator behind the canvas.

This is only half the problem with `load_gltf` etc, and it's arguably more confusing for a loading indicator to go away when everything's not done loading yet, but it's something.

**Comment by Weasy666** [comment]
As a starting point, i have added a `loading_screen` example to Bevy ([here](https://github.com/Weasy666/bevy/tree/loading_screen)). If you guys think the example is ok, i will make a PR to add it and then make a new PR in which i try to share that code/systems between examples.

**Comment by alice-i-cecile** [comment]
Migrating to #338 to address the remaining functionality.

**Comment by alice-i-cecile** [comment]
@Weasy666 can you PR that loading_screen example to Bevy itself? Seems genuinely useful to show-off.

**Comment by Weasy666** [comment]
There is already an open PR since January. You can find it here in the message timeline.

**Comment by mockersf** [comment]
It depends what you mean by "slow". For me on the website, it takes 1.25 seconds:

https://github.com/user-attachments/assets/5de13eeb-068c-4ed5-b3d4-be36af2a78cd

There are four parts:

1. loading the wasm file, which took 370ms in my video. That plus loading other html/js files, that took ~450ms
2. start the Bevy app. Took 200ms
3. loading all the assets needed, which from the network log finished at around 1050ms. Took 400ms
4. compiling the shaders, which will take the rest of the "time to render something". Took 200ms

Depending on what's eating your duration, you have different actions:

1. loading the wasm file can take a long time depending on your network quality and your distance to the server. You can use a CDN to put it closer to your users, prefetch it in another page on your site so that it's already in cache or display a small animation while loading it so that it seems faster
2. To reduce start time of Bevy, you can try to disable the features you don't use. The examples on the website have all the default features enabled, you probably don't need them all. But there's probably not much you can do there, most of the time is *probably* spent getting the texture to render from the browser.
3. loading the assets can also take a long time if you have a lot of assets, or a bad network. you can try to load your assets as they are needed instead of at the start, to not block on having everything available
4. shader compilation can vary wildly between browsers. Try different browsers to find what works best for you. You can try to display first something that would compile a single shader, and compile the others after you displayed something initially
