### ISSUE TITLE
Book Structure && Dev Cycle ?

### ISSUE THREAD

**Issue by jbcurtin** [bevyengine/bevy-website#264]
Hi, found some time to look over the book. I'm really liking the layout. - I'm a little lost on the volume of contribution required. I see a lot of pages with TODO:
<img width="1440" alt="Screen Shot 2022-01-11 at 1 18 06 PM" src="https://user-images.githubusercontent.com/45219/148880432-2d71563f-84b8-4539-b1ce-1cf07c1823d5.png">

I also see a complete page on `alice-i-cecile:game-logic-chapter`. ( Woohoo! )
<img width="1440" alt="Screen Shot 2022-01-11 at 1 18 03 PM" src="https://user-images.githubusercontent.com/45219/148880610-4459da6f-15d7-4260-928b-4de891b4a8e4.png">

Would someone give me a quick rundown of the dev-cycle for `bevy-website`?

**Comment by alice-i-cecile** [comment]
Hi! I'm the lead of the new book project!

So the gist of the status is: the Welcome chapter is merged, the ECS chapter is effectively complete (check the PRs) and the game logic chapter has been started.

In order to move forward and collaborate more effectively, there are some technical and organizational challenges to overcome.

We need to make progress on the book less frustrating, more reliable, easier to review and easier to distribute across team members. Lots of ideas, and I'm going to be focusing on this now that the release is out.

I'll outline them in a tracking issue tomorrow; please feel free to come say hi on Discord too if you'd like to chat more casually!

**Comment by alice-i-cecile** [comment]
@jbcurtin I wrote up the tracking issue in #265. Closing this in favor of that tracking issue!
