### ISSUE TITLE
Add labels on issues & PRs

### ISSUE THREAD

**Issue by doup** [bevyengine/bevy-website#306]
Hi! I've been checking the issues with the idea of contributing and I noticed that almost no labels are used. It would be really useful to be able to differentiate the issue types. In my case, I wanted to do some small bugfixing (HTML/CSS/JS stuff)… or maybe some proof-reading of documentation; having some tags would be helpful.

**Comment by alice-i-cecile** [comment]
Definitely in favor of that.

I think we should have several "areas", like on the `bevy` repo:

- `Copyediting`
- `Documentation`
- `Website`
- `Build-System`
- `Meta`

@cart, you'll need to do this one yourself, since you're the only one with the appropriate permissions.

**Comment by cart** [comment]
I'm on board. How would you distinguish Documentation from Copyediting?

**Comment by cart** [comment]
Also wouldn't everything be in the "website" area, given that this is the "website" repo?

**Comment by cart** [comment]
Maybe organizing by section would be more descriptive?
* A-Book
* A-News
* A-Assets
* A-Home
* A-Build-System
* A-Meta

**Comment by alice-i-cecile** [comment]
> I'm on board. How would you distinguish Documentation from Copyediting?

The former is "Bevy specific technical knowledge", the latter is "your marketing text is wrong".

> Also wouldn't everything be in the "website" area, given that this is the "website" repo?

I was thinking this would be for things that require HTML / CSS skills.

> Maybe organizing by section would be more descriptive?

This may be good, but I was hoping we could split this out by required skill set somehow. Folks with web tech knowledge have a different set of areas they can  help with compared to Bevy experts compared to folks who are good at writing marketing material.

**Comment by cart** [comment]
> This may be good, but I was hoping we could split this out by required skill set somehow. Folks with web tech knowledge have a different set of areas they can help with compared to Bevy experts compared to folks who are good at writing marketing material.

Solid point. Maybe `A-Webdev` and `A-Content`? (combined with the relevant `A-Book` / `A-News` where appropriate)

**Comment by alice-i-cecile** [comment]
Yep I'm on board with that organization :)

**Comment by cart** [comment]
Hmm actually maybe `C-Webdev` and `C-Content`? `A-` is more for "domains" and `C-` is more for "issue type".

**Comment by cart** [comment]
Done! Feel free to keep the conversation going if you have more thoughts / tweaks.

**Comment by alice-i-cecile** [comment]
Okay so first pass:

- build system belongs under `C`, like webdev, because it requires a different set of skills. See #279 for an example.
- the line between content and docs feels unclear. See #262. I think that this could be fixed by clarifying the descriptions of each label.
- It's not exactly clear where "examples" issues belong: #279, #236
- issues about "the deployed docs" (e.g. #181) are very unclear to label
- I want a "Blocked" tag of some sort, for e.g. #175.
-  It's not clear where issues about the merch site belong, or what tag they'd use
- I want something akin to "code quality" or "developer experience" for e.g. #161.

**Comment by cart** [comment]
> build system belongs under C, like webdev, because it requires a different set of skills. See https://github.com/bevyengine/bevy-website/issues/279 for an example.

This conflicts with the `A-Build-System` label in the main bevy repo. Imo this could go either way, but id like to be consistent. I'm personally fine with it being an "area" because it is "distinct" from the other areas (especially in the main bevy repo). You can largely point to a folder and be like "this is where the build system is". Whereas you can't point somewhere and say this is where `C-Content` / `C-Webdev` / `C-Accessibility` / etc is (they are more "abstract" concepts). The line between `A` and `C` is definitely  blurry. If you have thoughts on clear definitions, lemme know.

>  the line between content and docs feels unclear. See https://github.com/bevyengine/bevy-website/issues/262. I think that this could be fixed by clarifying the descriptions of each label.

Yeah I think with the `A-X` + `C-Content` pattern, `C-Docs` has less meaning. Imo this feels "fine" because we can be more specific. Maybe we should just remove `C-Docs`?

> It's not exactly clear where "examples" issues belong: https://github.com/bevyengine/bevy-website/issues/279, https://github.com/bevyengine/bevy-website/issues/236

Imo its still `A-Book`. Whether or not its `C-Content` and / or something more specific like `C-Example-Code` is definitely worth thinking about. I'll probably defer to you here, given that you're working in this area more than me atm.

> I want a "Blocked" tag of some sort, for e.g. https://github.com/bevyengine/bevy-website/issues/175.

Good call. Just added `S-Blocked`

> It's not clear where issues about the merch site belong, or what tag they'd use

Given that its "barely" a part of the bevy-website repo (really just a hyperlink), I'm cool with considering this out of scope for now. We can cross that bridge when we come to it.

> I want something akin to "code quality" or "developer experience" for e.g. https://github.com/bevyengine/bevy-website/issues/161.

This feels less like "code quality" and more like `C-Enhancement`. I think thats what we'd use in the main bevy repo. We don't really distinguish between "private enhancements" vs "public enhancements" at the moment right? Given that changes often blur the lines here, idk if the distinction will be helpful in the majority of cases. Many "public enhancements" are often backed by "private enhancements". Open to discussion here though.

**Comment by alice-i-cecile** [comment]
> If you have thoughts on clear definitions, lemme know.

I generally think that we should have `A` reflect "subject matter expertise", and `C` reflect "generic skill set or category".  Build system feels akin to "examples", which also live in their own folder on the main repo.

> Maybe we should just remove C-Docs?

Agreed for this repo.

> This feels less like "code quality" and more like C-Enhancement. I think thats what we'd use in the main bevy repo. We don't really distinguish between "private enhancements" vs "public enhancements" at the moment right? Given that changes often blur the lines here, idk if the distinction will be helpful in the majority of cases. Many "public enhancements" are often backed by "private enhancements". Open to discussion here though.

On the main repo, things like this would be `Code-Quality` or `Usability`. `Enhancement`, at least in our little bubble, tends to mean something closer to "deliverable feature".

**Comment by cart** [comment]
> I generally think that we should have A reflect "subject matter expertise", and C reflect "generic skill set or category". Build system feels akin to "examples", which also live in their own folder on the main repo.

Yeah examples would definitely be `C-Example`. I buy that definition. And I guess "build system" could mean more than one thing within a given repo, which does make it more of a `C`. Im convinced. I'll make the change in both repos. 

> Agreed for this repo.

Done!

> On the main repo, things like this would be Code-Quality or Usability. Enhancement, at least in our little bubble, tends to mean something closer to "deliverable feature".

Yeah that seems like a solid interpretation. Imo `C-Code-Quality` should be reserved for "formatting, refactors, alignment with patterns, consistency, etc". Implementing "sorting by file name" functionality feels out of scope for that imo. `C-Usability` does seem reasonable though. Are you down to use that?

**Comment by cart** [comment]
(I just added C-Usability)

**Comment by alice-i-cecile** [comment]
> C-Usability does seem reasonable though. Are you down to use that?

Absolutely, thanks!

**Comment by doup** [comment]
Thanks! Much better now! :-)

Just a nit though, it should be `C-Accessibility` (not Access-**A**-bility). 😇

**Comment by cart** [comment]
Oops. Fixed!
