### ISSUE TITLE
Book: System Examples work without Person reference

### ISSUE THREAD

**Issue by dgb23** [bevyengine/bevy-website#4]
I noticed that the `greet_people` systems (both the foreach and the later query variation) compile and run just fine without the Person reference.

So: `fn greet_people(name: &Name)` `fn greet_people(time: Res<Time>, mut timer: ResMut<GreetTimer>, mut query: Query<&Name>)` work just like `fn greet_people(person: &Person, name: &Name)` and `fn greet_people(time: Res<Time>, mut timer: ResMut<GreetTimer>, mut query: Query<(&Person, &Name)>)`.

Is there a specific reason the author included the Person references here? It seems confusing to me.

**Comment by cart** [comment]
Yeah I knew this going into it. I wanted to illustrate the pattern of breaking up a "traditional" data structure into its core pieces (in this case the Person marker component and the Name component). I think including another system with `(&Dog, &Name)` would help illustrate the reuse and the value of the marker components. In this case, including "Person" in the query ensures we only run on entities with (Person, Name) instead of any entity with Name. 

However in practice to suppress the "unused variable" warning and reduce the amount of data accessed, we would actually write the query like this:
```rs
Query<With<Person, &Name>>
```
That runs on the same dataset, but only iterates over the Name components. I didnt use that approach  because I didnt want to over-complicate the query with `With` that early in the book.

I can definitely see how this is confusing. If you have suggestions let me know.

**Comment by dgb23** [comment]
> If you have suggestions let me know.

I think you answered it yourself!

> In this case, including "Person" in the query ensures we only run on entities with (Person, Name) instead of any entity with Name.

Maybe there is an opportunity here to show this in the tutorial. I personally have a "break things to learn things"-approach and find it very powerful and I feel like the tutorial is written with this mindset too.

So maybe introduce this "bug" by declaring an entity with a name component which we don't want to greet!

**Comment by visualcode-t** [comment]
I don't think there is a real issue here. It seems pretty clear in the book, to me. But, if clarification is needed, I do see two ways to clarify this. First, is to add the Dog entity, as already mentioned. The second would be a little more specific:

> The parameters we pass in to a "system function" define what entities the system runs on. In this case, greet_people will run on all entities with the Person and Name component.

Could be...

> The parameters we pass in to a "system function" define what entities the system runs on. In this case, greet_people will run on all entities **that have both** the Person and Name component.

And for queries:

> Now our App should properly greet all People, once every two seconds!

Could be...

> Now our App should properly greet all **_Persons_ that have a name component**, once every two seconds!

**Comment by alice-i-cecile** [comment]
Closing out; this is no longer how our syntax works :)
