### ISSUE TITLE
Setup page recomends dynamic linking for linux, but has no mention of incremental building.

### ISSUE THREAD

**Issue by ZBemo** [bevyengine/bevy-website#642]
It appears to me that in recent versions of rust, debug mode builds use incremental compilation by default. By my understanding, this means that, while using a sufficiently up-to-date rust compiler, when you're recompiling your game after updating it, bevy is already not rebuilt, and is instead simply linked into your program, similar to what happens with bevy_dylib.

Although I might simply be misunderstanding or missing something, it seems to me that the current setup page has no indication of this fact, and believe it may be worthwhile to at least mention that incremental compilation with a good linker will achieve a goal similar to that of using the bevy_dylib feature, but with the added benefit of not having to manage toggling a feature for bevy on and off when building for release/debug, as cargo handles that automatically with incremental builds.

**Comment by TrialDragon** [comment]
Hmm, looking into this Incremental Compilation has been enabled by default (technically it was before, but it got enabled and disabled a bit because bugs were discovered) since the release of Rust 1.60 per [this Rust blog post](https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#incremental-compilation-status), but also that Incremental Compilation and Dynamic Libraries don't appear to be mutually exclusive in their performance benefits per [this article](https://robert.kra.hn/posts/2022-09-09-speeding-up-incremental-rust-compilation-with-dylibs/) Perhaps mention that Incremental Compilation does exist and that default compilation is better than it was before, but that the Dynamic Library will still grant a benefit to your compilations.

**Comment by alice-i-cecile** [comment]
> Hmm, I think this is ultimately distracting. Users don't need to worry about things that are on by default.

Neat little digression, but I think it's important to keep the flow for new users as smooth as posible.
