### ISSUE TITLE
Screen shot on the home page uses obsolete for-each system syntax

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#75]
The [main page](https://bevyengine.org/) screen shot of the syntax is now obsolete, as for-each systems have been deprecated.

The replacement code is:

```rust
struct Component;

fn system(query: Query<Entity, Component>){
}
```

But that doesn't demonstrate how to actually use a Query object smoothly.

Something like:

```rust
struct Component;

fn system(query: Query<Entity, Component>){
  for (e, c) in query.iter(){
  }
}
```

Is probably the most representative of actual use now.

**Comment by cart** [comment]
yup good call! ill see which one fits the image best.

(also its `Query<(Entity, Component)>`)

**Comment by jamadazi** [comment]
@cart do you have any preference/requirement for what font should be used for the image?

I'd like to make a PR, but just want to confirm any requirements for the visual aesthetic / appearence first.

**Comment by cart** [comment]
Awesome! I'd like it to be as similar to the current one as possible (ex: same colors and same font). I believe the font is Fira Mono

**Comment by alice-i-cecile** [comment]
Based on [discussion](https://discord.com/channels/691052431525675048/743559241461399582/805122636761137223) in #documentation, the rough consensus was that the following example captured the spirit of Bevy's syntax well while being more approachable to beginners who don't know ECS jargon. 

```rust
fn system(
  players: Query<&Player>,
  game: Res<Game>
) {    
    for player in players.iter() {
        play(player, game);
    }
}
```

We could do this, a rough adaptation of the existing code, as proposed in the first bit of this issue, or something in between. That's your judgement call though @cart.

If we end up wanting lots of this sort of thing or a simple reproducible workflow, it was mentioned that swapping to a tool like [carbon.now.sh](https://carbon.now.sh/?bg=rgba%28255%2C255%2C255%2C0%29&t=3024-night&wt=sharp&l=rust&ds=false&dsyoff=100px&dsblur=68px&wc=false&wa=false&pv=0px&ph=0px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=struct%2520Resource%253B%250Astruct%2520Component%253B%250A%250Afn%2520system%28%250A%2520%2520%2520%2520resource%253A%2520Res%253CResource%253E%252C%250A%2520%2520%2520%2520query%253A%2520Query%253C%28Entity%252C%2520Component%29%253E%250A%29%2520%257B%250A%2520%2520for%2520%28e%252C%2520c%29%2520in%2520query.iter%28%29%257B%250A%2520%2520%257D%250A%257D) might be a good choice.

**Comment by cart** [comment]
> simple reproducible workflow

I just used inkscape to generate the svg:

1. add the text using the text tool
2. convert the text to a "path" using "Path -> Object To Path"
3. assign the colors to the appropriate places
4. resize the document to the context using "File -> Document Properties -> Resize page to content"

I prefer that over carbon because:

1. The SVG carbon exports uses "svg text", which means the browser controls the font / falls back when a font doesn't exist. The current approach "bakes" the font into curves to avoid this problem.
2. I'd want more control over the layout / spacing / color / margins than it provides.

> Based on discussion in #documentation, the rough consensus was that the following example captured the spirit of Bevy's syntax well while being more approachable to beginners who don't know ECS jargon.

The point of the image was to quickly and minimally anchor ECS jargon into Bevy's syntax, not to introduce people to all of bevy's ecs features (ex: resources and query iteration). My preference would be for something more like this:

```rust
struct Component;
fn system(
  query: Query<(Entity, &Component)>
) {
}
```
